### ISSUE TITLE
[Feature Request] Take method

### ISSUE THREAD

**Issue by kyp44** [Idolf/takeable#2]
As I have an immediate need for it, I thought about creating this exact crate, but I would love for `Takeable` to have a `take` method to move the item out and have the `Takeable` just panic if the users tries to access the item again, which would pretty much just require calling the underlying `Option::take`. This is useful when you need to move something out of a struct but only have a mutable reference to it, for example in a `drop` method. In this case the containing struct is going to be dropped anyway so it would be wasteful to have to re-assign the inner item using a closure in `Takeable::borrow` or `Takeable::borrow_result`.

**Comment by TethysSvensson** [comment]
I don't really consider this project maintained. If you want you are welcome to submit a PR and I will accept it and do a release. Alternatively you are also welcome to take over the project from me.

**Comment by kyp44** [comment]
Actually I'd be happy to just take over the crate if you're no longer interested in maintaining it. I haven't published a crate before so it will be a good chance for me to learn that process using a simple crate.

**Comment by TethysSvensson** [comment]
@kyp44 How about I transfer the github repo to you, and once you've set up your account in crates.io, I'll transfer the crate to you there as well?

**Comment by kyp44** [comment]
@TethysSvensson That sounds good to me. I did go ahead and create and account on crates.io since I could just login using my GitHub account. My name there (and in real life!) is Dan Whitman. Let me know if you run into any issues with the transfer. I appreciate you giving me the opportunity to administer my first public crate.

**Comment by TethysSvensson** [comment]
@kyp44 Can you link to your crates.io account? Like this? https://crates.io/users/TethysSvensson

**Comment by kyp44** [comment]
@TethysSvensson Looks like it's here: [https://crates.io/users/kyp44](https://crates.io/users/kyp44). Sorry, I didn't realize that crates.io seems to have no way to search for authors.

**Comment by kyp44** [comment]
@TethysSvensson Thanks for the transfer!
